### ISSUE TITLE
Colosseum Brazier

### ISSUE THREAD

**Issue by nnra6864** [NNStdios/Katana#1]
You are mostly done @eldrejko, @Trowee should make materials and send it.

**Comment by nnra6864** [comment]
A few more issues:
1. Transform wasn't applied
2. Origin should be at the bottom center of the model, just like all the other lights:

<img width="431" height="624" alt="Image" src="https://github.com/user-attachments/assets/e1d81ec4-2b38-4f33-b4da-8819a5901179" />

<img width="220" height="603" alt="Image" src="https://github.com/user-attachments/assets/78bd3c82-5fd6-4fa1-8ef6-14d4905b3b17" />

@eldrejko @Trowee

**Comment by Trowee** [comment]
Here are 2k materials, @eldrejko will handle transform and origin placement.

[Brazier_Materials.zip](https://github.com/user-attachments/files/22348804/Brazier_Materials.zip)

**Comment by nnra6864** [comment]
Mats are excellent, waiting for corrected transforms and origin @eldrejko

**Comment by Trowee** [comment]
[Brazier_Model.zip](https://github.com/user-attachments/files/22370430/Brazier_Model.zip) Here is model with fixed transforms and origin.

**Comment by eldrejko** [comment]
Fixed Topology issues, @Trowee should fix textures bro im sorry 👍

**Comment by nnra6864** [comment]
@Trowee I have the project cuz it was too big for gh, will croc it to you tmr.
UV maps are remade so you'll have to fix mats.

**Comment by nnra6864** [comment]
Almost there, it's still slightly floating and has to be moved down.
@Trowee

**Comment by nnra6864** [comment]
@Trowee still not fixed, and this time it ain't @eldrejko's fault either:

<img width="1223" height="948" alt="Image" src="https://github.com/user-attachments/assets/3e8da7bf-0e9f-42f8-be3a-1d0c075febc8" />

<img width="1187" height="704" alt="Image" src="https://github.com/user-attachments/assets/81479a06-9af6-48d8-bf05-0de8eb840927" />

**Comment by Trowee** [comment]
[Download](https://www.mediafire.com/file/5d2cen40gvlwi76/Brazier.zip/file)

<img width="943" height="1023" alt="Image" src="https://github.com/user-attachments/assets/f3a30fe4-9531-4112-9275-ae73b1e8136c" />

**Comment by nnra6864** [comment]
Ok, it all lgtm now, great job.
I got 2 minor complaints/ideas.
1. The wood looks kinda flat ngl, I think a better material could be used for this:

<img width="770" height="664" alt="Image" src="https://github.com/user-attachments/assets/a9b6bc2c-9acb-41b0-8a0c-41e6e5644755" />

2. Could be just me, but I think this looks a bit better if there's a slight cyan tint added to the silver part:

<img width="728" height="913" alt="Image" src="https://github.com/user-attachments/assets/d076e11c-a187-4267-9b99-6116c08559a4" />

<img width="594" height="793" alt="Image" src="https://github.com/user-attachments/assets/5962db2d-e940-4497-bc5e-5ebdb1fd7e0b" />

lmk what your thoughts are on this and we should be able to finish w this tmr @eldrejko @Trowee

**Comment by Trowee** [comment]
I agree for wood but I think cyan tint wouldn't suit it very well.

**Comment by nnra6864** [comment]
Ok, so make it then.

**Comment by nnra6864** [comment]
Forgot to attach an image, it looks excellent.

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/f6b0dbdc-fedb-4651-a1d9-ef102cd0b24e" />
